version: '3.8'

services:
  app:
    build: .
    container_name: nestjs_app
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=moviesdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: moviesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:6
    container_name: redis_cache
    ports:
      - '6379:6379'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
